version: '3'

services:
  server:
    image: node:16-slim
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm run dev
